# This is a basic workflow to help you get started with Actions

name: Release Pipeline for edisongearnest.com

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: ng version
        run: ng version

      - name: NPM Install
        run: npm install

      - name: NPM Build
        run: npm run build