# name: WORKFLOW - Release Pipeline for edisongearnest.com

# on: 
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]
#   workflow_dispatch:
#     inputs:
#       refToBuild:
#         type: string
#         description: 'Branch, tag or commit SHA1 to build'
#         default: 'master'
#       forceDeploy:
#         type: boolean
#         description: 'Force Deploy'
#         default: false
#       logLevel:
#         type: choice
#         description: 'Log Level'
#         default: 'error'
#         options:
#         - info
#         - warning
#         - error

# jobs:
#   website-deployment:
#     name: Website Deployment
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2.3.4 # Necessary to access local action

#       - name: Build And Deploy
#         id: build-and-deploy
#         uses: ./.github/actions/release-action.yml
#         with:
#           refToBuild: ${{ inputs.refToBuild }}
#           forceDeploy: ${{ inputs.forceDeploy }}
#           logLevel: ${{ inputs.logLevel }}
#           host: ${{ secrets.HOST }}
#           username: ${{ secrets.SSH_USER }}
#           password: ${{ secrets.PASSWORD }}
#       # - name: Output Output
#       #   run: echo "${{ steps.build-and-deploy.outputs.test }}"
