# This is a basic workflow to help you get started with Actions

name: Release Pipeline for edisongearnest.com

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: pwd
        run: pwd

      - name: ls
        run: ls

      - name: NPM Install
        run: npm install

      - name: NPM Build
        run: npm run build-prod